### ISSUE TITLE
First run: Cannot Connect to Update.Appwork.org! Check Internet Settings

### ISSUE THREAD

**Issue by hrmtc** [jlesage/docker-jdownloader-2#108]
Hi.

When I run Jdownloader for first time shows the following message:

![image](https://user-images.githubusercontent.com/58194010/189700226-8db70cba-bd55-4aed-86aa-bdae26d6cb4c.png)

**This Error is caused for**
`org.jdownloader.update.launcher.JDLauncherFailedException:** java.lang.NoClassDefFoundError: org/jdownloader/startup/Main
	at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:675)
	at org.jdownloader.update.launcher.SecondLevelLauncher.init(SecondLevelLauncher.java:461)
	at org.jdownloader.update.launcher.SecondLevelLauncher.runMain(SecondLevelLauncher.java:229)
	at org.jdownloader.update.launcher.JDLauncherViaClassLoader.main(JDLauncherViaClassLoader.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jdownloader.updatev2.JDClassLoaderLauncher.main(JDClassLoaderLauncher.java:152)
	at org.jdownloader.update.launcher.JDLauncher.main(JDLauncher.java:8)
Caused by: java.lang.NoClassDefFoundError: org/jdownloader/startup/Main
	at org.jdownloader.launcher.StandaloneLauncher.launchJDownloader(StandaloneLauncher.java:133)
	at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:637)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.jdownloader.startup.Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 11 more`
 
I've checked that inside my container I can resolve update.appwork.org

![image](https://user-images.githubusercontent.com/58194010/189701028-681cd246-4905-4bec-a878-660f4bcfee07.png)

What else can I try?

Thanks!

**Comment by hrmtc** [comment]
Hi.

Finally I've figure it out: My Sophos Firewall was denying connections to 176.9.34.43. 
I made a rule exception and now works great.
I leave this here in case that could be helpful others.

Cheers.
