### ISSUE TITLE
DDownload mirrors "waiting for host"

### ISSUE THREAD

**Issue by Just-Ch33s3** [jlesage/docker-jdownloader-2#114]
Hello and thanks for your effort creating this practical container!
DDownload mirror downloads (using a premium account) only result in a "waiting for host" message for me, other hosters like uploaded.net seem to work
can't reproduce that error on a standalone JDownloader installation, seems to only affect the container version... 
Are you able to reproduce this issue ?

**Comment by Just-Ch33s3** [comment]
Yes, several times and after restart, i've wiped the container aswell and did a fresh install, no change
Also tried to force http over https in extended options for ddownload, no change after all
I'll stick to another hoster in the meantime

**Comment by jlesage** [comment]
It's hard for me to test without an account...
Maybe you can look the log file at `/config/logs/output.log` inside the container to see if there is anything useful.

**Comment by Just-Ch33s3** [comment]
I'd be happy to give you one, please let me know how to reach you personally via DM! : )
My first thoughts were also bashing into that container, but 
sudo docker exec -it $id bash
doesnt seem to work, which way do you use to get into your instance ?

**Comment by jlesage** [comment]
> I'd be happy to give you one, please let me know how to reach you personally via DM! : )

Humm not sure I have a such way.

> so i'd just need the path to cat the output

You can run `tail -f /config/logs/output.log`, then try to add you account and see what's happening.

**Comment by hebaio** [comment]
I ran into the same issue, while inserting a ddownload.com premium account. 
`tail -f /config/logs/output.log` did not show anything really helpful. 

But the jdownload debug logs show something:
`------------------------Thread: 84:accountCheck_ddownload.com_jd.plugins.hoster.DdownloadCom.log-----------------------
--ID:84TS:1674249554177-1/20/23 10:19:14 PM -  [jd.controlling.AccountController(updateAccountInfo)] -> Account Update: XXX@XXX.com->ddownload.com(jd.plugins.hoster.DdownloadCom|46664)
--ID:84TS:1674249554178-1/20/23 10:19:14 PM -  [org.jdownloader.plugins.components.XFileSharingProBasic(loginWebsite)] -> Full login required
--ID:84TS:1674249554179-1/20/23 10:19:14 PM -  [org.jdownloader.plugins.components.XFileSharingProBasic(loginWebsite)] -> Performing full website login attempt: 1/3 | Multiple attempts will only happen if a captcha is required
--ID:84TS:1674249554198-1/20/23 10:19:14 PM -  [jd.http.Browser(openRequestConnection)] -> 
Caller: org.jdownloader.plugins.components.antiDDoSForHost.sendRequest(antiDDoSForHost.java:318)
org.jdownloader.plugins.components.antiDDoSForHost.getPage(antiDDoSForHost.java:184)
org.jdownloader.plugins.components.XFileSharingProBasic.getPage(XFileSharingProBasic.java:3004)
org.jdownloader.plugins.components.XFileSharingProBasic.getPage(XFileSharingProBasic.java:3000)
org.jdownloader.plugins.components.XFileSharingProBasic.loginWebsite(XFileSharingProBasic.java:4209)
jd.plugins.hoster.DdownloadCom.loginWebsite(DdownloadCom.java:290)
org.jdownloader.plugins.components.XFileSharingProBasic.fetchAccountInfoWebsite(XFileSharingProBasic.java:3490)
jd.plugins.hoster.DdownloadCom.fetchAccountInfoWebsite(DdownloadCom.java:370)
org.jdownloader.plugins.components.XFileSharingProBasic.fetchAccountInfo(XFileSharingProBasic.java:3484)
jd.controlling.AccountController.updateAccountInfo(AccountController.java:325)
jd.controlling.accountchecker.AccountChecker$AccountCheckJob.check(AccountChecker.java:47)
jd.controlling.accountchecker.AccountChecker$1.run(AccountChecker.java:155)
BrowserID:1|BrowserParentID:-1|RequestID:1|URL:https://ddownload.com/login.html
----------------Request Information-------------
URL: https://ddownload.com/login.html
Host: ddownload.com
Connection-Timeout: 20000ms
Read-Timeout: 60000ms
----------------ConnectionExceptions-------------------------
0:ddownload.com/0.0.0.0:443|java.net.ConnectException(Connection refused (Connection refused))|retrySSL:null
----------------Request-------------------------
-------------Not Connected Yet!-----------------

----------------Response Information------------
-------------Not Connected Yet!------------------


--ID:84TS:1674249554198-1/20/23 10:19:14 PM -  [] -> Exception thrown at jd.http.Browser.openRequestConnection(Browser.java:1950):
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:607)
	at org.appwork.utils.net.httpconnection.HTTPConnectionImpl.connect(HTTPConnectionImpl.java:950)
	at org.appwork.utils.net.httpconnection.HTTPConnectionImpl.finalizeConnect(HTTPConnectionImpl.java:1320)
	at jd.http.Request.connect(Request.java:355)
	at jd.http.Request.connect(Request.java:342)
	at jd.http.Browser.openRequestConnection(Browser.java:1914)
	at jd.http.Browser.openRequestConnection(Browser.java:1770)
	at org.jdownloader.plugins.components.antiDDoSForHost.sendRequest(antiDDoSForHost.java:318)
	at org.jdownloader.plugins.components.antiDDoSForHost.getPage(antiDDoSForHost.java:184)
	at org.jdownloader.plugins.components.XFileSharingProBasic.getPage(XFileSharingProBasic.java:3004)
	at org.jdownloader.plugins.components.XFileSharingProBasic.getPage(XFileSharingProBasic.java:3000)
	at org.jdownloader.plugins.components.XFileSharingProBasic.loginWebsite(XFileSharingProBasic.java:4209)
	at jd.plugins.hoster.DdownloadCom.loginWebsite(DdownloadCom.java:290)
	at org.jdownloader.plugins.components.XFileSharingProBasic.fetchAccountInfoWebsite(XFileSharingProBasic.java:3490)
	at jd.plugins.hoster.DdownloadCom.fetchAccountInfoWebsite(DdownloadCom.java:370)
	at org.jdownloader.plugins.components.XFileSharingProBasic.fetchAccountInfo(XFileSharingProBasic.java:3484)
	at jd.controlling.AccountController.updateAccountInfo(AccountController.java:325)
	at jd.controlling.accountchecker.AccountChecker$AccountCheckJob.check(AccountChecker.java:47)
	at jd.controlling.accountchecker.AccountChecker$1.run(AccountChecker.java:155)

--ID:84TS:1674249554199-1/20/23 10:19:14 PM -  [jd.plugins.PluginForHost(handleAccountException)] -> PluginDetails(jd.plugins.hoster.DdownloadCom|46664)
--ID:84TS:1674249554199-1/20/23 10:19:14 PM -  [] -> Exception thrown at jd.plugins.PluginForHost.handleAccountException(PluginForHost.java:364):
jd.http.Browser$BrowserException: Caller: org.jdownloader.plugins.components.antiDDoSForHost.sendRequest(antiDDoSForHost.java:318)
org.jdownloader.plugins.components.antiDDoSForHost.getPage(antiDDoSForHost.java:184)
org.jdownloader.plugins.components.XFileSharingProBasic.getPage(XFileSharingProBasic.java:3004)
org.jdownloader.plugins.components.XFileSharingProBasic.getPage(XFileSharingProBasic.java:3000)
org.jdownloader.plugins.components.XFileSharingProBasic.loginWebsite(XFileSharingProBasic.java:4209)
jd.plugins.hoster.DdownloadCom.loginWebsite(DdownloadCom.java:290)
org.jdownloader.plugins.components.XFileSharingProBasic.fetchAccountInfoWebsite(XFileSharingProBasic.java:3490)
jd.plugins.hoster.DdownloadCom.fetchAccountInfoWebsite(DdownloadCom.java:370)
org.jdownloader.plugins.components.XFileSharingProBasic.fetchAccountInfo(XFileSharingProBasic.java:3484)
jd.controlling.AccountController.updateAccountInfo(AccountController.java:325)
jd.controlling.accountchecker.AccountChecker$AccountCheckJob.check(AccountChecker.java:47)
jd.controlling.accountchecker.AccountChecker$1.run(AccountChecker.java:155)
BrowserID:1|BrowserParentID:-1|RequestID:1|URL:https://ddownload.com/login.html
----------------Request Information-------------
URL: https://ddownload.com/login.html
Host: ddownload.com
Connection-Timeout: 20000ms
Read-Timeout: 60000ms
----------------ConnectionExceptions-------------------------
0:ddownload.com/0.0.0.0:443|java.net.ConnectException(Connection refused (Connection refused))|retrySSL:null
----------------Request-------------------------
-------------Not Connected Yet!-----------------

----------------Response Information------------
-------------Not Connected Yet!------------------


	at jd.http.Browser.openRequestConnection(Browser.java:1961)
	at jd.http.Browser.openRequestConnection(Browser.java:1770)
	at org.jdownloader.plugins.components.antiDDoSForHost.sendRequest(antiDDoSForHost.java:318)
	at org.jdownloader.plugins.components.antiDDoSForHost.getPage(antiDDoSForHost.java:184)
	at org.jdownloader.plugins.components.XFileSharingProBasic.getPage(XFileSharingProBasic.java:3004)
	at org.jdownloader.plugins.components.XFileSharingProBasic.getPage(XFileSharingProBasic.java:3000)
	at org.jdownloader.plugins.components.XFileSharingProBasic.loginWebsite(XFileSharingProBasic.java:4209)
	at jd.plugins.hoster.DdownloadCom.loginWebsite(DdownloadCom.java:290)
	at org.jdownloader.plugins.components.XFileSharingProBasic.fetchAccountInfoWebsite(XFileSharingProBasic.java:3490)
	at jd.plugins.hoster.DdownloadCom.fetchAccountInfoWebsite(DdownloadCom.java:370)
	at org.jdownloader.plugins.components.XFileSharingProBasic.fetchAccountInfo(XFileSharingProBasic.java:3484)
	at jd.controlling.AccountController.updateAccountInfo(AccountController.java:325)
	at jd.controlling.accountchecker.AccountChecker$AccountCheckJob.check(AccountChecker.java:47)
	at jd.controlling.accountchecker.AccountChecker$1.run(AccountChecker.java:155)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:607)
	at org.appwork.utils.net.httpconnection.HTTPConnectionImpl.connect(HTTPConnectionImpl.java:950)
	at org.appwork.utils.net.httpconnection.HTTPConnectionImpl.finalizeConnect(HTTPConnectionImpl.java:1320)
	at jd.http.Request.connect(Request.java:355)
	at jd.http.Request.connect(Request.java:342)
	at jd.http.Browser.openRequestConnection(Browser.java:1914)
	... 13 more

--ID:84TS:1674249554200-1/20/23 10:19:14 PM -  [jd.http.Browser(setProxySelector)] -> Use local proxy: Direct wished: Direct
`

So the connection is refused by ddownload.com but not sure why. I tested several network configs and VPN configs, but note worked. Same configs work on a regular Windows machine however.

**Comment by Just-Ch33s3** [comment]
Just found a way; routing expressvpn through UDP seems to block certain connections to Ddownload, setting it to TCP solved it
