### ISSUE TITLE
[Bug] Provide a short description of the bug here

### ISSUE THREAD

**Issue by droopified** [jlesage/docker-jdownloader-2#162]
### Current Behavior

java.lang.NoClassDefFoundError: org/appwork/swing/trayicon/TrayMouseListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at jd.gui.swing.jdgui.JDGui.<init>(JDGui.java:237)
	at jd.gui.swing.jdgui.JDGui.<init>(JDGui.java:154)
	at jd.gui.swing.jdgui.JDGui$35.edtRun(JDGui.java:1700)
	at jd.gui.swing.jdgui.JDGui$35.edtRun(JDGui.java:1696)
	at org.appwork.utils.swing.EDTHelper.run(EDTHelper.java:119)
	at org.appwork.utils.swing.EDTHelper.start(EDTHelper.java:154)
	at org.appwork.utils.swing.EDTHelper.waitForEDT(EDTHelper.java:168)
	at org.appwork.utils.swing.EDTHelper.getReturnValue(EDTHelper.java:100)
	at jd.gui.swing.jdgui.JDGui.init(JDGui.java:1704)
	at jd.SecondLevelLaunch$11.edtRun(SecondLevelLaunch.java:966)
	at jd.SecondLevelLaunch$11.edtRun(SecondLevelLaunch.java:956)
	at org.appwork.utils.swing.EDTHelper.run(EDTHelper.java:119)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.appwork.swing.trayicon.TrayMouseListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 38 more

### Expected Behavior

i cant start. it is also saying a license needs to be updated? the only logins i have are for archive and youtube. 

### Steps To Reproduce

restarted

### Environment

- OS:unraid
- OS version:6.12.3
- CPU:i3 3700?
- Docker version:?
- Device model:
- Browser/OS:chrome/brave

### Container creation

unraid

### Container log

```text
│ Application Version:   n/a                                           │
    │ Docker Image Version:  23.06.1                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] service 'logmonitor' is disabled.
[supervisor  ] loading service 'logrotate'...
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.13.1 - built May 16 2023 17:43:49
[xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Sun Jul 30 10:10:41 2023
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTP connections on port 5800.
[supervisor  ] starting service 'openbox'...
[xvnc        ] Sun Jul 30 10:10:46 2023
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[supervisor  ] starting service 'app'...
[supervisor  ] all services started.
[xvnc        ] Sun Jul 30 10:11:05 2023
[xvnc        ]  VNCSConnST:  closing /tmp/vnc.sock: Clean disconnection
[xvnc        ]  EncodeManager: Framebuffer updates: 5
[xvnc        ]  EncodeManager:   Tight:
[xvnc        ]  EncodeManager:     Solid: 11 rects, 2.85104 Mpixels
[xvnc        ]  EncodeManager:            176 B (1:64797.1 ratio)
[xvnc        ]  EncodeManager:     Bitmap RLE: 2 rects, 320 pixels
[xvnc        ]  EncodeManager:                 99 B (1:13.1717 ratio)
[xvnc        ]  EncodeManager:   Total: 13 rects, 2.85136 Mpixels
[xvnc        ]  EncodeManager:          275 B (1:41474.9 ratio)
[xvnc        ]  Connections: closed: /tmp/vnc.sock
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc        ] Sun Jul 30 10:14:10 2023
[xvnc        ]  VNCSConnST:  closing /tmp/vnc.sock: Clean disconnection
[xvnc        ]  EncodeManager: Framebuffer updates: 453
[xvnc        ]  EncodeManager:   CopyRect:
[xvnc        ]  EncodeManager:     Copies: 38 rects, 1.94333 Mpixels
[xvnc        ]  EncodeManager:             608 B (1:12785.8 ratio)
[xvnc        ]  EncodeManager:   Tight:
[xvnc        ]  EncodeManager:     Solid: 212 rects, 10.6195 Mpixels
[xvnc        ]  EncodeManager:            3.3125 KiB (1:12523.8 ratio)
[xvnc        ]  EncodeManager:     Bitmap RLE: 35 rects, 9.755 kpixels
[xvnc        ]  EncodeManager:                 1.11719 KiB (1:34.4755 ratio)
[xvnc        ]  EncodeManager:     Indexed RLE: 385 rects, 168.001 kpixels
[xvnc        ]  EncodeManager:                  34.4014 KiB (1:19.2075 ratio)
[xvnc        ]  EncodeManager:   Tight (JPEG):
[xvnc        ]  EncodeManager:     Full Colour: 181 rects, 1.40292 Mpixels
[xvnc        ]  EncodeManager:                  1.71407 MiB (1:3.12345 ratio)
[xvnc        ]  EncodeManager:   Total: 851 rects, 14.1435 Mpixels
[xvnc        ]  EncodeManager:          1.75257 MiB (1:30.7908 ratio)
[xvnc        ]  Connections: closed: /tmp/vnc.sock
[xvnc        ]  ComparingUpdateTracker: 28.3017 Mpixels in / 9.67651 Mpixels out
[xvnc        ]  ComparingUpdateTracker: (1:2.92478 ratio)
[xvnc        ] Sun Jul 30 10:14:11 2023
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
```

**Comment by droopified** [comment]
think ifixed it by deleting temp. is it safe to disable update from within jdownloader and letting the docker update from unraid?

**Comment by magnu5** [comment]
> think ifixed it by deleting temp. is it safe to disable update from within jdownloader and letting the docker update from unraid?

deleting tmp/synthlibs seems to have fixed it.

**Comment by jlesage** [comment]
> is it safe to disable update from within jdownloader and letting the docker update from unraid?

Note that an update of the container image doesn't update JDownloader.  JDownloader is not a versioned software, meaning that multiple parts of the software can be updated separately and dynamically.

**Comment by jlesage** [comment]
So removing the `tmp` folder fixed your issue ?

**Comment by magnu5** [comment]
> So removing the `tmp` folder fixed your issue ?

not OP, but yes. The problem was with a license for the Synthetica skin, more info [here](https://board.jdownloader.org/showthread.php?p=505448). Seems to be fixed in a update but for me removing the `tmp/synthlibs` and restarting the container fixed it.

**Comment by StormPooper** [comment]
I had to stop the container and delete the following to get it to work for me:

>  Close JDownloader, delete the folders
tmp , update and libs, and the file Core.jar and start JDownloader again.
> https://board.jdownloader.org/showpost.php?p=505455&postcount=6
