### ISSUE TITLE
Synlology-Docker: JD keeps carshing

### ISSUE THREAD

**Issue by chigy110** [jlesage/docker-jdownloader-2#232]
### Current Behavior

org.jdownloader.update.launcher.JDLauncherFailedException: java.lang.NoClassDefFoundError: Could not initialize class org.jdownloader.gui.views.downloads.table.DownloadsTableModel
	at org.jdownloader.update.launcher.SecondLevelLauncher.launchJDownloader(SecondLevelLauncher.java:709)
	at org.jdownloader.update.launcher.SecondLevelLauncher.init(SecondLevelLauncher.java:487)
	at org.jdownloader.update.launcher.SecondLevelLauncher.runMain(SecondLevelLauncher.java:237)
	at org.jdownloader.update.launcher.JDLauncherViaClassLoader.main(JDLauncherViaClassLoader.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jdownloader.updatev2.JDClassLoaderLauncher.main(JDClassLoaderLauncher.java:152)
	at org.jdownloader.update.launcher.JDLauncher.main(JDLauncher.java:8)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jdownloader.gui.views.downloads.table.DownloadsTableModel
	at org.jdownloader.gui.views.downloads.DownloadsPanel.<init>(DownloadsPanel.java:63)
	at org.jdownloader.gui.views.downloads.DownloadsView.<init>(DownloadsView.java:17)
	at jd.gui.swing.jdgui.JDGui.initComponents(JDGui.java:509)
	at jd.gui.swing.jdgui.JDGui.<init>(JDGui.java:233)
	at jd.gui.swing.jdgui.JDGui.<init>(JDGui.java:154)
	at jd.gui.swing.jdgui.JDGui$35.edtRun(JDGui.java:1697)
	at jd.gui.swing.jdgui.JDGui$35.edtRun(JDGui.java:1692)
	at org.appwork.utils.swing.EDTHelper.run(EDTHelper.java:119)
	at org.appwork.utils.swing.EDTHelper.start(EDTHelper.java:154)
	at org.appwork.utils.swing.EDTHelper.waitForEDT(EDTHelper.java:168)
	at org.appwork.utils.swing.EDTHelper.getReturnValue(EDTHelper.java:100)
	at jd.gui.swing.jdgui.JDGui.init(JDGui.java:1702)
	at jd.SecondLevelLaunch$12.edtRun(SecondLevelLaunch.java:986)
	at jd.SecondLevelLaunch$12.edtRun(SecondLevelLaunch.java:982)
	at org.appwork.utils.swing.EDTHelper.run(EDTHelper.java:119)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Environment

- OS: DSM
- OS version: DSM 7.1.1-42962 Update 6
- CPU: INTEL Pentium N3710
- Docker version: 20.10.3.1308
- Device model:
- Browser/OS:

### Container creation

docker run -d \
    --name=jdownloader-2 \
    -p 5800:5800 \
    -v /docker/appdata/jdownloader-2:/config:rw \
    -v /home/user/Downloads:/output:rw \
    jlesage/jdownloader-2

### Container log

```text
Suche
[supervisor  ] loading service 'logrotate'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'xcompmgr'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'webauth'...
[supervisor  ] service 'webauth' is disabled.
[supervisor  ] loading service 'audiorecorder'...
[supervisor  ] service 'audiorecorder' is disabled.
[supervisor  ] loading service 'pulseaudio'...
[supervisor  ] service 'pulseaudio' is disabled.
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] service 'logmonitor' is disabled.
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.13.1 - built Aug 31 2024 13:06:50
[xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Sun Oct 20 11:52:49 2024
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'openbox'...
[supervisor  ] starting service 'xcompmgr'...
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTP connections on port 5800.
[supervisor  ] starting service 'app'...
[supervisor  ] all services started.
[xvnc        ] Sun Oct 20 11:52:59 2024
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc        ] Sun Oct 20 11:54:15 2024
[xvnc        ]  ComparingUpdateTracker: 238.51 Mpixels in / 2.63281 Mpixels out
[xvnc        ]  ComparingUpdateTracker: (1:90.5915 ratio)
```

**Comment by QQ7QQ7** [comment]
Had the same issue but I was able to fix it with the file creation mentioned in the troubleshooting: [https://github.com/jlesage/docker-jdownloader-2?tab=readme-ov-file#jdownloader-fails-to-start](https://github.com/jlesage/docker-jdownloader-2?tab=readme-ov-file#jdownloader-fails-to-start). Maybe this helps you too?

**Comment by zalloumfam** [comment]
thank you @QQ7QQ7 that worked for me as well. If @chigy110  can chime in so this can get closed
