### ISSUE TITLE
JDownloader2 during install / update

### ISSUE THREAD

**Issue by DaLeberkasPepi** [jlesage/docker-jdownloader-2#99]
Since today i get following error message when JDownloader2 tries to verify installation.
I also tried it with a empty folder to single out some specific settings in my config and the error message persists.

`org.jdownloader.update.SelfUpdateException: Selftest has been terminated unexpectedly
	at org.jdownloader.update.SelfUpdateClient.finishSelfUpdate(SelfUpdateClient.java:329)
	at org.jdownloader.update.UpdateManager.runFinishSelfUpdate(UpdateManager.java:961)
	at org.jdownloader.update.DefaultCallbackHandler.onResults(DefaultCallbackHandler.java:304)
	at org.jdownloader.update.UpdateManager.runUpdateLoop(UpdateManager.java:1336)
	at org.jdownloader.update.UpdateManager$7.run(UpdateManager.java:395)
	at java.lang.Thread.run(Thread.java:748)
`

Are there other people how get the same error message like me?

**Comment by DaLeberkasPepi** [comment]
it works again. Seems like a problem on the side of jdownloader or something
